### ISSUE TITLE
Failing to create logs

### ISSUE THREAD

**Issue by dbrianhendrix** [mbridak/WinterFieldDayLogger#26]
When I press "Generate Logs", I get the following and the adi file is missing most of the contacts.
I am running this on a MacBook Pro using Sonoma.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fdlogger/__main__.py", line 2450, in generate_logs
    self.adif()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fdlogger/__main__.py", line 2225, in adif
    state = self.get_state(hissection)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fdlogger/__main__.py", line 2055, in get_state
    state = self.secState[section]
            ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'CA'
Abort trap: 6

**Comment by mbridak** [comment]
Hi. What's the version number of the logger that you're using?

From the looks of it, I think you might have used the Field Day logger instead of the Winter Field Day logger.
The lines in the traceback all reference python3.12/site-packages/fdlogger/main.py and the line numbers line up with that code base.

I'm going to make changes to the Field Day logger code and update that package.

Let me know if you agree. You can double check the program name and version by looking at the top of logger window.

**Comment by mbridak** [comment]
Oh, and would you be willing to email me your .db file?

**Comment by mbridak** [comment]
I corrected the error in the FD logger. 
My guess is one of your contacts has a bad arrl/rac section. This caused a key error in the lookup of the state.
You can update the Field Day logger and regenerate the ADI. Or correct the incorrect logged section. Or both.

**Comment by dbrianhendrix** [comment]
Thank you, Michael!

I just got home and saw your emails. I reinstalled fdlogger and the “Generate Logs” worked perfectly. I saw a YouTube video on your software but it only mentioned flogger and Linux. However, I was able to install it and use it on macOS. I was not aware there was a Winter Field Day version which I will install.

Thanks for the great software and quick fix. It was my first WFD and the software worked great for logging on macOS.


D. Brian Hendrix
veteran  |  mac guy  |  birder  |  coffee snob

Tennessee Naturalist, first
Senior Linux Engineer, second

615.336.4573
***@***.*** ***@***.***>
￼

**Comment by mbridak** [comment]
Glad it worked. I'll close out this issue then. Thanks for reporting the problem. If you plan on operating in other contests, I'd point you too [Not1MM](https://github.com/mbridak/not1mm). That's where 90% of my development time is directed.

73, Mike K6GTE.

**Comment by dbrianhendrix** [comment]
Awesome!

Just installed it on my Mac Mini to test install. I got the following but it appears to work. I’ll install it on my MacBook Pro later and test it with CAT to my Xiegu G90.

Thanks!

========================================================================

Mac-mini:Not1MM brianhendrix$ not1mm
[13:31:46] WARNING __main__ - <module> Line 3092: debugging off
sh: xdg-icon-resource: command not found
sh: xdg-icon-resource: command not found
sh: xdg-icon-resource: command not found
sh: xdg-desktop-menu: command not found
2024-02-12 13:31:47.142 Python[10611:886192] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

========================================================================


D. Brian Hendrix
veteran  |  mac guy  |  birder  |  coffee snob

Tennessee Naturalist, first
Senior Linux Engineer, second

615.336.4573
***@***.*** ***@***.***>
￼
